# Generated by Django 4.0.1 on 2022-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_date', models.DateTimeField()),
                ('blog_text', models.TextField(max_length=2000)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
